### ISSUE TITLE
i have "HTTP ERROR 500" on Cpanel 

### ISSUE THREAD

**Issue by victorn3ss** [sirn-se/phrity-net-stream#3]
Could not open socket to "tcp://139.99.71.***:27001": Server is closed.
and respone ERROR 500

this is error log

[20-Aug-2023 19:55:13 UTC] PHP Fatal error:  Uncaught ErrorException: stream_socket_client(): Unable to connect to tcp://139.99.71.***:27001 (Connection refused) in /home/projrvrw/public_html/vendor/phrity/net-stream/src/SocketClient.php:84
Stack trace:
#0 [internal function]: Phrity\Util\ErrorHandler->Phrity\Util\{closure}()
#1 /home/projrvrw/public_html/vendor/phrity/net-stream/src/SocketClient.php(84): stream_socket_client()
#2 /home/projrvrw/public_html/vendor/phrity/util-errorhandler/src/Phrity/Util/ErrorHandler.php(60): Phrity\Net\SocketClient->Phrity\Net\{closure}()
#3 /home/projrvrw/public_html/vendor/phrity/net-stream/src/SocketClient.php(86): Phrity\Util\ErrorHandler->with()
#4 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(289): Phrity\Net\SocketClient->connect()
#5 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(209): WebSocket\Client->connect()
#6 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(157): WebSocket\Client->send()
#7 /home/projrvrw/public_html/vendor/scai/php-webrcon/src/WebRconClass.php(62): WebSocket\Client->text()
#8 /home/projrvrw/public_html/index.php(13): Scai\WebRcon\WebRconClass->send()
#9 {main}

Next Phrity\Net\StreamException: Client could not connect to "tcp://139.99.71.***:27001". in /home/projrvrw/public_html/vendor/phrity/net-stream/src/SocketClient.php:86
Stack trace:
#0 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(289): Phrity\Net\SocketClient->connect()
#1 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(209): WebSocket\Client->connect()
#2 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(157): WebSocket\Client->send()
#3 /home/projrvrw/public_html/vendor/scai/php-webrcon/src/WebRconClass.php(62): WebSocket\Client->text()
#4 /home/projrvrw/public_html/index.php(13): Scai\WebRcon\WebRconClass->send()
#5 {main}

Next WebSocket\ConnectionException: Could not open socket to "tcp://139.99.71.***:27001": Server is closed. in /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php:293
Stack trace:
#0 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(209): WebSocket\Client->connect()
#1 /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php(157): WebSocket\Client->send()
#2 /home/projrvrw/public_html/vendor/scai/php-webrcon/src/WebRconClass.php(62): WebSocket\Client->text()
#3 /home/projrvrw/public_html/index.php(13): Scai\WebRcon\WebRconClass->send()
#4 {main}
  thrown in /home/projrvrw/public_html/vendor/phrity/websocket/lib/Client.php on line 293

**Comment by sirn-se** [comment]
The most relevant error here is "Connection refused". That is, the server you're trying to connect to have refused your attempt to connect. Reason might be that the server do not allow port or schema used, or require some kind of authentication to accept connections.

Exception when client fails to connect is expected behavior of this library.
